//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Product.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int pid { get; set; }
        public string pname { get; set; }
        public Nullable<decimal> pprice { get; set; }
        public string pimage { get; set; }
        public Nullable<bool> pisdemand { get; set; }
        public string pcname { get; set; }
        public string psupply { get; set; }
    }
}
